version: '3'
services:
  wildscribe-api:
    image: wildscribe 
    deploy:
        resources:
            limits:
              cpus: "0.50"
              memory: 512M
            reservations:
              cpus: "0.25"
              memory: 128M
    environment:
      - ENV=PROD
      - PORT=8080
      - ADVENTUREGATEWAY=adventure-microservice:8083
      - USERGATEWAY=user-microservice:8082
    ports:
      - "8080:8080"  # Adjust the ports as needed
    networks:
      - wildscribe-network

  adventure-microservice:
    image: adventure 
    deploy:
        resources:
            limits:
              cpus: "0.50"
              memory: 512M
            reservations:
              cpus: "0.25"
              memory: 128M
    environment:
      - ENV=PROD
      - PORT=8083
      - MONGOURI=MONGOURI
      - DATABASE=golangAPI
      - COLLECTION=adventures

    networks:
      - wildscribe-network

  user-microservice:
    image: user
    deploy:
        resources:
            limits:
              cpus: "0.50"
              memory: 512M
            reservations:
              cpus: "0.25"
              memory: 128M 
    environment:
      - ENV=PROD
      - PORT=8082
      - MONGOURI=MONGOURI
      - DATABASE=golangAPI
      - COLLECTION=users

    networks:
      - wildscribe-network

networks:
  wildscribe-network:
