version: '3'
services:

  mongodb:
    image: mongo
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 512M
        reservations:
          cpus: "0.20"
          memory: 256M
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    ports:
      - "27017:27017" 
    networks:
      - wildscribe-network


  wildscribe-api:
    build:
      context: /
      dockerfile: /wildscribe/Dockerfile
    image: wildscribe 
    deploy:
        resources:
            limits:
              cpus: "0.10"
              memory: 512M
            reservations:
              cpus: "0.10"
              memory: 128M
    environment:
      - ENV=PROD
      - PORT=8080
      - ADVENTUREGATEWAY=adventure-microservice:8083
      - USERGATEWAY=user-microservice:8082
    ports:
      - "8080:8080"  # Adjust the ports as needed
    networks:
      - wildscribe-network

  adventure-microservice:
    build:
      context: /
      dockerfile: /adventure/Dockerfile
    image: adventure 
    deploy:
        resources:
            limits:
              cpus: "0.10"
              memory: 512M
            reservations:
              cpus: "0.10"
              memory: 128M
    environment:
      - ENV=PROD
      - PORT=8083
      - MONGOURI=mongodb://admin:adminpassword@mongodb:27017
      - DATABASE=golangAPI
      - COLLECTION=adventures

    networks:
      - wildscribe-network

  user-microservice:
    build:
      context: /
      dockerfile:  /user/Dockerfile
    image: user
    deploy:
        resources:
            limits:
              cpus: "0.30"
              memory: 512M
            reservations:
              cpus: "0.30"
              memory: 128M 
    environment:
      - ENV=PROD
      - PORT=8082
      - MONGOURI=mongodb://admin:adminpassword@mongodb:27017
      - DATABASE=golangAPI
      - COLLECTION=users

    networks:
      - wildscribe-network


networks:
  wildscribe-network:
