version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.21.3
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: go build -o main.exe $(go list ./wildscribe/cmd/...)
      - run: docker build -t wildscribe -f wildscribe/Dockerfile .


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
