version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: cd /wildscribe
      - run: docker build -t wildscribe .
      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Build and Test
          command: |
            docker-compose up --build -d

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
