version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: docker build -t wildscribe -f wildscribe/Dockerfile .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
