apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventure-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adventure
  template:
    metadata:
      labels:
        app: adventure
    spec:
      containers:
      - name: adventure-container
        image: wildscribecr.azurecr.io/adventure
        ports:
        - containerPort: 8083
        resources:
          limits:
            cpu: "0.50"
            memory: "512Mi"
          requests:
            cpu: "0.25"
            memory: "128Mi"
        env:
        - name: ENV
          value: PROD