apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: steamedmicrobe373/user:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082